 
server:
  port: 8090
  
custom:
 google-store:
  appPage:
   - https://play.google.com/store/apps/details?id=
  title: #extract from  index, output string
   - 0 
   - 0
  logo: #extract from list index, output string
   - 12
   - 1 
  screenShot:  #extract from list index, output list of string
   - 12
   - 0 
  description:  #extract from list index, output string
   - 10
   - 0
   - 1 
  shortDescription:  #extract from list index, output string
   - 10
   - 1
   - 1
  userID: #extract from list index, output string
   - 12 
   - 5
   - 0
   - 0
  company: #extract from list index, output string
   - 12 
   - 5
   - 1
  email: #extract from list index, output string
   - 12 
   - 5
   - 2
   - 0
  installed: #extract from list index, output string
   - 12 
   - 9
   - 2 
  category: #extract from list index, output string
   - 12 
   - 13
   - 0
   - 0
  publishDate: #extract from list index, output string
   - 12 
   - 8
   - 1
  updatedDate: #extract from list index, output string
   - 12 
   - 36
  ratingAvg: #extract from list index, output string 
   - 6 
   - 0
   - 1 
  rating1: #extract from list index, output string 
   - 6 
   - 1
   - 1 
   - 1
  rating2: #extract from list index, output string 
   - 6 
   - 1
   - 2 
   - 1  
  rating3: #extract from list index, output string 
   - 6 
   - 1
   - 3 
   - 1  
  rating4: #extract from list index, output string 
   - 6 
   - 1
   - 4 
   - 1  
  rating5: #extract from list index, output string 
   - 6 
   - 1
   - 5 
   - 1   
  ratingTotal: #extract from list index, output string 
   - 6  
   - 2 
   - 1   
  reviewTotal: #extract from list index, output string 
   - 6 
   - 3 
   - 1
  reviewID: #extract from list index, output string 
   - 9 
   - 1
  reviewName: #extract from list index, output string 
   - 9 
   - 0
  reviewRating: #extract from list index, output string 
   - 2
  reviewMessage: #extract from list index, output string 
   - 4 
  reviewDate: #extract from list index, output string 
   - 5 
   - 0
  reviewVersion: #extract from list index, output string 
   - 10 
   
   
  appSize: #extract from list index, output string 
   - 0 
  appVersion: #extract from list index, output string 
   - 1 
  appSupport: #extract from list index, output string 
   - 2   
  
    